apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monorepo-demo-infra
  source:
    chart: kafka
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: 20.5.0
    helm:
      parameters:
        - name: auth.enabled
          value: 'false'
      releaseName: kafka
  destination:
    namespace: monorepo-demo
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-beta
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monorepo-demo-infra
  source:
    chart: kafka
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: 20.5.0
    helm:
      parameters:
        - name: auth.enabled
          value: 'false'
      releaseName: kafka
  destination:
    namespace: monorepo-demo
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monorepo-demo-infra
  source:
    chart: kafka
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: 20.5.0
    helm:
      parameters:
        - name: auth.enabled
          value: 'false'
      releaseName: kafka
  destination:
    namespace: monorepo-demo
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
