apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deployment.yaml

commonLabels:
  app: docs-beta

nameSuffix: -beta

images:
- name: docs
  newName: ghcr.io/vedi/monorepo-demo/docs
  newTag: 1.1.0-beta.0

resources:
- ../../base
