apiVersion: v1
kind: Secret
metadata:
  name: monorepo-demo-repo-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: monorepo-demo-repo-config
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "some-secret-name"
  project: "monorepo-demo"
  type: "git"
  url: "https://github.com/vedi/monorepo-versioning-gitops.git"
