apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deployment.yaml

commonLabels:
  app: api-dev

nameSuffix: -dev

images:
- name: api
  newName: ghcr.io/vedi/monorepo-demo/api
  newTag: dev-1b62960712df46465ef6192a6a7f1d197898592a

resources:
- ../../base
